package model;
// Generated 27 oct. 2015 12:19:47 by Hibernate Tools 4.3.1


import model.User;
import java.util.Date;

/**
 * Deliveryservice generated by hbm2java
 */
public class Deliveryservice  implements java.io.Serializable {


     private int id;
     private User user;
     private String city;
     private Date date;
     private String size;
     private String transport;

    public Deliveryservice() {
    }

	
    public Deliveryservice(int id, User user, String city, Date date) {
        this.id = id;
        this.user = user;
        this.city = city;
        this.date = date;
    }
    public Deliveryservice(int id, User user, String city, Date date, String size, String transport) {
       this.id = id;
       this.user = user;
       this.city = city;
       this.date = date;
       this.size = size;
       this.transport = transport;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getTransport() {
        return this.transport;
    }
    
    public void setTransport(String transport) {
        this.transport = transport;
    }




}


