package model;
// Generated 27 oct. 2015 12:19:47 by Hibernate Tools 4.3.1


import model.User;
import java.util.Date;

/**
 * Prerequest generated by hbm2java
 */
public class Prerequest  implements java.io.Serializable {


     private int id;
     private User user;
     private String city;
     private String picup;
     private String destination;
     private String object;
     private Date date;
     private String size;
     private String transport;

    public Prerequest() {
    }

	
    public Prerequest(int id, User user, String city, String object) {
        this.id = id;
        this.user = user;
        this.city = city;
        this.object = object;
    }
    public Prerequest(int id, User user, String city, String object, Date date, String size, String transport, String picup, String destination) {
       this.id = id;
       this.user = user;
       this.city = city;
       this.picup = picup;
       this.destination = destination;
       this.object = object;
       this.date = date;
       this.size = size;
       this.transport = transport;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    
     public String getPicup() {
        return this.picup;
    }
    
    public void setPicup(String picup) {
        this.picup = picup;
    }
    
       public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public String getObject() {
        return this.object;
    }
    
    public void setObject(String object) {
        this.object = object;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getTransport() {
        return this.transport;
    }
    
    public void setTransport(String transport) {
        this.transport = transport;
    }




}


