package model;
// Generated 27 oct. 2015 12:19:47 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String prenom;
     private String email;
     private String pwd;
     private String confirmpwd;
     private int statut;
     private Date created;

    public User() {
    }

    public User(String nom, String prenom, String email, String pwd,String confirmpwd, int statut, Date created) {
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.pwd = pwd;
       this.confirmpwd=confirmpwd;
       this.statut = statut;
       this.created = created;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
     public String getConfirmpwd() {
        return this.confirmpwd;
    }
    
    public void setConfirmpwd(String confirmpwd) {
        this.confirmpwd = confirmpwd;
    }
    
    public int getStatut() {
        return this.statut;
    }
    
    public void setStatut(int statut) {
        this.statut = statut;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }




}


